<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Chatify\Traits\UUID;

class ChMessage extends Model
{
    // UUID trait might be missing too, so we'll implement UUID generation manually if needed or skip it for now if ID is auto-generated by DB (it's UUID in migration).
    // The migration said $table->uuid('id')->primary();
    // We should probably ensure the ID is cast to string.

    protected $table = 'ch_messages';

    protected $fillable = [
        'id',
        'from_id',
        'to_id',
        'body',
        'attachment',
        'seen',
    ];

    public $incrementing = false;
    protected $keyType = 'string';

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = (string) \Illuminate\Support\Str::uuid();
            }
        });
    }
}
